### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by eleimt** [sigmdel/other_releases#1]
Hello.  I read the article, I flash it using the Flash Tool but it doesn’t work.

The firmware is installed successfully, but I do not receive a response from the "AT" command from the Arduino IDE.  Moreover, if I write something incorrect, I get the answer “ERROR”.

Can I ask you to help me with this?

**Comment by sigmdel** [comment]
Could it be as simple as setting line endings to both NL & CR in the Arduino serial monitor?
